# Generated by Django 4.2.7 on 2026-01-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('daily_calories_target', models.PositiveIntegerField(blank=True, null=True, verbose_name='Günlük Kalori Hedefi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dietitian', models.ForeignKey(limit_choices_to={'user_type': 'dietitian'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_diet_plans', to=settings.AUTH_USER_MODEL, verbose_name='Diyetisyen')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL, verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Diyet Planı',
                'verbose_name_plural': 'Diyet Planları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Besin Adı')),
                ('portion_size', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Porsiyon Miktarı')),
                ('unit', models.CharField(choices=[('g', 'gram'), ('ml', 'mililitre'), ('adet', 'adet'), ('su_bardagi', 'su bardağı'), ('cay_bardagi', 'çay bardağı'), ('yemek_kasigi', 'yemek kaşığı'), ('cay_kasigi', 'çay kaşığı'), ('dilim', 'dilim'), ('porsiyon', 'porsiyon')], default='g', max_length=20, verbose_name='Birim')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kalori')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Protein (g)')),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Karbonhidrat (g)')),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Yağ (g)')),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Lif (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'dietitian'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Besin',
                'verbose_name_plural': 'Besinler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Kahvaltı'), ('morning_snack', 'Kuşluk'), ('lunch', 'Öğle Yemeği'), ('afternoon_snack', 'İkindi'), ('dinner', 'Akşam Yemeği'), ('evening_snack', 'Gece Atıştırması')], max_length=20, verbose_name='Öğün Tipi')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Önerilen Saat')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diets.dietplan', verbose_name='Diyet Planı')),
            ],
            options={
                'verbose_name': 'Öğün',
                'verbose_name_plural': 'Öğünler',
                'ordering': ['diet_plan', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Miktar')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.food', verbose_name='Besin')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='diets.meal', verbose_name='Öğün')),
            ],
            options={
                'verbose_name': 'Öğün Besini',
                'verbose_name_plural': 'Öğün Besinleri',
            },
        ),
    ]
