# Generated by Django 4.2.7 on 2026-01-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('user_type', models.CharField(choices=[('dietitian', 'Diyetisyen'), ('patient', 'Hasta')], max_length=20, verbose_name='Kullanıcı Tipi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkek'), ('F', 'Kadın'), ('O', 'Diğer')], max_length=1, verbose_name='Cinsiyet')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Boy (cm)')),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mevcut Kilo (kg)')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hedef Kilo (kg)')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Tıbbi Durumlar/Notlar')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('dietitian', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'dietitian'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Diyetisyen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hasta Profili',
                'verbose_name_plural': 'Hasta Profilleri',
            },
        ),
        migrations.CreateModel(
            name='DietitianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Hakkında')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Uzmanlık Alanı')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Deneyim (Yıl)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dietitians/', verbose_name='Fotoğraf')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Diploma No')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietitian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diyetisyen Profili',
                'verbose_name_plural': 'Diyetisyen Profilleri',
            },
        ),
    ]
