# Generated by Django 4.2.7 on 2026-01-18 12:24

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_users(apps, schema_editor):
    """
    Varsayılan kullanıcılar oluşturur:
    1. Admin superuser (admin@admin.com / admin)
    2. Ali kullanıcısı (ali@ali.com / ali)
    """
    User = apps.get_model('accounts', 'User')
    DietitianProfile = apps.get_model('accounts', 'DietitianProfile')
    PatientProfile = apps.get_model('accounts', 'PatientProfile')

    # 1. Admin superuser oluştur
    if not User.objects.filter(email='admin@admin.com').exists():
        admin_user = User.objects.create(
            email='admin@admin.com',
            first_name='Admin',
            last_name='User',
            user_type='dietitian',
            is_staff=True,
            is_superuser=True,
            is_active=True,
            password=make_password('admin')
        )

        DietitianProfile.objects.create(
            user=admin_user,
            bio='Sistem Yöneticisi',
            specialization='Genel',
            experience_years=0
        )

        print(">>> Admin superuser olusturuldu!")
        print(">>> Email: admin@admin.com")
        print(">>> Sifre: admin")

    # 2. Ali kullanıcısı oluştur (hasta)
    if not User.objects.filter(email='ali@ali.com').exists():
        ali_user = User.objects.create(
            email='ali@ali.com',
            first_name='Ali',
            last_name='Yilmaz',
            user_type='patient',
            is_staff=False,
            is_superuser=False,
            is_active=True,
            password=make_password('ali')
        )

        PatientProfile.objects.create(
            user=ali_user,
            height=175,
            current_weight=80,
            target_weight=75
        )

        print(">>> Ali kullanicisi olusturuldu!")
        print(">>> Email: ali@ali.com")
        print(">>> Sifre: ali")


def delete_default_users(apps, schema_editor):
    """Migration geri alınırsa kullanıcıları sil"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email__in=['admin@admin.com', 'ali@ali.com']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_users, delete_default_users),
    ]
