# Generated by Django 4.2.7 on 2026-01-18 12:43

from datetime import date, time, timedelta
from decimal import Decimal

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.models import Q
from django.utils import timezone


MOCK_TAG = '[mock-seed-v2]'

DIETITIAN_SPECS = [
    {
        'email': 'ayse@ayse.com',
        'password': 'ayse',
        'first_name': 'Ayse',
        'last_name': 'Kaya',
        'bio': f'Spor beslenmesi ve kilo yonetimi odakli calismalar. {MOCK_TAG}',
        'specialization': 'Spor Beslenmesi',
        'experience_years': 8,
        'phone': '+90 532 100 10 01',
        'address': 'Kadikoy, Istanbul',
        'city': 'Istanbul',
        'license_number': 'DYT-MOCK-1001',
        'photo': 'dietitians/mock-ayse.jpg',
    },
    {
        'email': 'mehmet.demir@mockdiet.com',
        'password': 'mockdiet123',
        'first_name': 'Mehmet',
        'last_name': 'Demir',
        'bio': f'Metabolik sendrom ve diyabet beslenmesi uzmani. {MOCK_TAG}',
        'specialization': 'Metabolik Hastaliklar',
        'experience_years': 12,
        'phone': '+90 532 100 10 02',
        'address': 'Cankaya, Ankara',
        'city': 'Ankara',
        'license_number': 'DYT-MOCK-1002',
        'photo': 'dietitians/mock-mehmet.jpg',
    },
    {
        'email': 'zeynep.yildiz@mockdiet.com',
        'password': 'mockdiet123',
        'first_name': 'Zeynep',
        'last_name': 'Yildiz',
        'bio': f'Cocuk beslenmesi ve alerji diyetleri konusunda deneyimli. {MOCK_TAG}',
        'specialization': 'Cocuk Beslenmesi',
        'experience_years': 6,
        'phone': '+90 532 100 10 03',
        'address': 'Bornova, Izmir',
        'city': 'Izmir',
        'license_number': 'DYT-MOCK-1003',
        'photo': 'dietitians/mock-zeynep.jpg',
    },
    {
        'email': 'ahmet.sahin@mockdiet.com',
        'password': 'mockdiet123',
        'first_name': 'Ahmet',
        'last_name': 'Sahin',
        'bio': f'Kardiyovaskuler saglik ve anti-aging programlari. {MOCK_TAG}',
        'specialization': 'Kardiyovaskuler Saglik',
        'experience_years': 15,
        'phone': '+90 532 100 10 04',
        'address': 'Nilufer, Bursa',
        'city': 'Bursa',
        'license_number': 'DYT-MOCK-1004',
        'photo': 'dietitians/mock-ahmet.jpg',
    },
    {
        'email': 'fatma.arslan@mockdiet.com',
        'password': 'mockdiet123',
        'first_name': 'Fatma',
        'last_name': 'Arslan',
        'bio': f'Hamilelik ve emzirme donemi beslenme danismani. {MOCK_TAG}',
        'specialization': 'Hamilelik Beslenmesi',
        'experience_years': 10,
        'phone': '+90 532 100 10 05',
        'address': 'Muratpasa, Antalya',
        'city': 'Antalya',
        'license_number': 'DYT-MOCK-1005',
        'photo': 'dietitians/mock-fatma.jpg',
    },
    {
        'email': 'berk.can@mockdiet.com',
        'password': 'mockdiet123',
        'first_name': 'Berk',
        'last_name': 'Can',
        'bio': f'Kas kazanimi ve performans odakli planlama uzmani. {MOCK_TAG}',
        'specialization': 'Performans Beslenmesi',
        'experience_years': 7,
        'phone': '+90 532 100 10 06',
        'address': 'Konak, Izmir',
        'city': 'Izmir',
        'license_number': 'DYT-MOCK-1006',
        'photo': 'dietitians/mock-berk.jpg',
    },
]

PATIENT_NAMES = [
    ('Elif', 'Celik'),
    ('Can', 'Aydin'),
    ('Selin', 'Kurt'),
    ('Burak', 'Ozdemir'),
    ('Deniz', 'Yilmaz'),
    ('Ece', 'Aksoy'),
    ('Mert', 'Koc'),
    ('Irem', 'Erdogan'),
    ('Emre', 'Cetin'),
    ('Aylin', 'Polat'),
    ('Oguz', 'Karaca'),
    ('Gizem', 'Yildirim'),
    ('Kerem', 'Acar'),
    ('Pinar', 'Basaran'),
    ('Onur', 'Gunes'),
    ('Ceyda', 'Durmaz'),
    ('Baris', 'Ozkan'),
    ('Naz', 'Sen'),
    ('Alper', 'Kilic'),
    ('Esra', 'Ozgur'),
    ('Tolga', 'Yaman'),
    ('Duygu', 'Tekin'),
    ('Cem', 'Aslan'),
    ('Merve', 'Kara'),
    ('Kaan', 'Dogan'),
    ('Seda', 'Aras'),
    ('Murat', 'Tas'),
    ('Cansu', 'Ates'),
    ('Ufuk', 'Eren'),
    ('Begum', 'Kaya'),
]

MEDICAL_NOTES = [
    'Insulin direnci takipte.',
    'Hipotiroid gecmisi var.',
    'Mide hassasiyeti nedeniyle ogun aralari onemli.',
    'Laktoz intoleransi notu mevcut.',
    'Gece vardiyasi nedeniyle duzensiz ogun saatleri.',
    'Kolesterol takibi yapiliyor.',
]

FOOD_SPECS = [
    ('Mock Yulaf Ezmesi', '100.00', 'g', '389.00', '16.90', '66.30', '6.90', '10.60'),
    ('Mock Izgara Tavuk Gogsu', '100.00', 'g', '165.00', '31.00', '0.00', '3.60', '0.00'),
    ('Mock Yumurta', '1.00', 'adet', '78.00', '6.30', '0.60', '5.30', '0.00'),
    ('Mock Muz', '1.00', 'adet', '105.00', '1.30', '27.00', '0.40', '3.10'),
    ('Mock Brokoli', '100.00', 'g', '34.00', '2.80', '7.00', '0.40', '2.60'),
    ('Mock Somon', '100.00', 'g', '208.00', '20.40', '0.00', '13.40', '0.00'),
    ('Mock Badem', '30.00', 'g', '170.00', '6.00', '6.00', '15.00', '3.50'),
    ('Mock Elma', '1.00', 'adet', '95.00', '0.50', '25.00', '0.30', '4.40'),
    ('Mock Pirinc', '100.00', 'g', '130.00', '2.70', '28.20', '0.30', '0.40'),
    ('Mock Zeytinyagi', '15.00', 'ml', '120.00', '0.00', '0.00', '14.00', '0.00'),
    ('Mock Kefir', '200.00', 'ml', '110.00', '8.00', '8.00', '4.00', '0.00'),
    ('Mock Tam Bugday Ekmegi', '1.00', 'dilim', '68.00', '3.20', '12.50', '1.10', '1.90'),
    ('Mock Avokado', '100.00', 'g', '160.00', '2.00', '8.50', '14.70', '6.70'),
    ('Mock Ceviz', '20.00', 'g', '131.00', '3.00', '2.80', '13.00', '1.20'),
    ('Mock Nohut', '100.00', 'g', '164.00', '8.90', '27.40', '2.60', '7.60'),
    ('Mock Yogurt', '200.00', 'ml', '122.00', '8.50', '9.20', '5.00', '0.00'),
    ('Mock Kinoa', '100.00', 'g', '120.00', '4.40', '21.30', '1.90', '2.80'),
    ('Mock Hindi Gogus', '100.00', 'g', '135.00', '29.00', '0.00', '1.00', '0.00'),
]

CATEGORY_SPECS = [
    ('Mock Kilo Yonetimi', 'mock-kilo-yonetimi', f'Kilo yonetimine odakli yazi grubu. {MOCK_TAG}'),
    ('Mock Sporcu Beslenmesi', 'mock-sporcu-beslenmesi', f'Performans odakli beslenme icerikleri. {MOCK_TAG}'),
    ('Mock Klinik Beslenme', 'mock-klinik-beslenme', f'Klinik vakalara yonelik beslenme notlari. {MOCK_TAG}'),
    ('Mock Hamilelik Donemi', 'mock-hamilelik-donemi', f'Hamilelik ve emzirme odakli icerikler. {MOCK_TAG}'),
]

MEAL_TEMPLATES = [
    ('breakfast', time(8, 0), 'Kahvalti: protein + lif dengesi.'),
    ('morning_snack', time(10, 30), 'Kusluk: hafif ara ogun.'),
    ('lunch', time(13, 0), 'Ogle: ana ogun, sebze ve protein odakli.'),
    ('afternoon_snack', time(16, 0), 'Ikindi: enerji dengeleme ara ogunu.'),
    ('dinner', time(19, 0), 'Aksam: dengeli ve hafif menu.'),
    ('evening_snack', time(21, 30), 'Gece atistirmasi: kontrollu porsiyon.'),
]

APPOINTMENT_SLOTS = [
    time(9, 0),
    time(10, 0),
    time(11, 0),
    time(13, 30),
    time(14, 30),
    time(15, 30),
    time(16, 30),
]


def _to_decimal(value):
    return Decimal(str(value))


def _create_or_update_dietitians(apps):
    User = apps.get_model('accounts', 'User')
    DietitianProfile = apps.get_model('accounts', 'DietitianProfile')

    dietitians = []
    now = timezone.now()

    for idx, spec in enumerate(DIETITIAN_SPECS):
        user_defaults = {
            'first_name': spec['first_name'],
            'last_name': spec['last_name'],
            'user_type': 'dietitian',
            'is_staff': False,
            'is_superuser': False,
            'is_active': True,
            'password': make_password(spec['password']),
            'date_joined': now - timedelta(days=300 + (idx * 17)),
            'last_login': now - timedelta(days=idx),
        }
        user, _ = User.objects.update_or_create(email=spec['email'], defaults=user_defaults)

        DietitianProfile.objects.update_or_create(
            user=user,
            defaults={
                'bio': spec['bio'],
                'specialization': spec['specialization'],
                'experience_years': spec['experience_years'],
                'phone': spec['phone'],
                'address': spec['address'],
                'city': spec['city'],
                'license_number': spec['license_number'],
                'photo': spec['photo'],
            },
        )
        dietitians.append(user)

    return dietitians


def _create_or_update_patients(apps, dietitians):
    User = apps.get_model('accounts', 'User')
    PatientProfile = apps.get_model('accounts', 'PatientProfile')

    patients = []
    now = timezone.now()
    genders = ['F', 'M', 'O']

    for idx, (first_name, last_name) in enumerate(PATIENT_NAMES):
        if idx == 0:
            email = 'elif@patient.com'
            raw_password = '123456'
        else:
            email = f"{first_name.lower()}.{last_name.lower()}@mockpatient.com"
            raw_password = 'mockhasta123'

        assigned_dietitian = dietitians[idx % len(dietitians)]

        current_weight = _to_decimal(58 + ((idx * 3) % 35))
        target_weight = current_weight - _to_decimal(4 + (idx % 7))
        if target_weight < _to_decimal('45'):
            target_weight = _to_decimal('45')

        user, _ = User.objects.update_or_create(
            email=email,
            defaults={
                'first_name': first_name,
                'last_name': last_name,
                'user_type': 'patient',
                'is_staff': False,
                'is_superuser': False,
                'is_active': True,
                'password': make_password(raw_password),
                'date_joined': now - timedelta(days=200 + (idx * 5)),
                'last_login': now - timedelta(days=(idx % 12)),
            },
        )

        profile, _ = PatientProfile.objects.update_or_create(
            user=user,
            defaults={
                'dietitian': assigned_dietitian,
                'date_of_birth': date(1986 + (idx % 18), (idx % 12) + 1, (idx % 27) + 1),
                'gender': genders[idx % len(genders)],
                'height': _to_decimal(155 + (idx % 33)),
                'current_weight': current_weight,
                'target_weight': target_weight,
                'medical_conditions': f"{MEDICAL_NOTES[idx % len(MEDICAL_NOTES)]} {MOCK_TAG}",
                'phone': f"+90 53{(idx % 10)} {(100 + idx):03d} {(200 + idx):03d} {(10 + idx % 90):02d}",
            },
        )
        patients.append({'user': user, 'profile': profile, 'dietitian': assigned_dietitian})

    return patients


def _create_or_update_measurements(apps, patient_rows):
    Measurement = apps.get_model('patients', 'Measurement')
    today = date.today()

    for idx, payload in enumerate(patient_rows):
        patient = payload['user']
        base_weight = _to_decimal(payload['profile'].current_weight)

        for point in range(6):
            measurement_date = today - timedelta(days=(5 - point) * 14)
            weight = base_weight + _to_decimal((5 - point) * 0.4)

            Measurement.objects.update_or_create(
                patient=patient,
                date=measurement_date,
                defaults={
                    'weight': weight,
                    'body_fat_percentage': _to_decimal(19 + (idx % 10) + (5 - point) * 0.2),
                    'muscle_mass': _to_decimal(28 + (idx % 8) + point * 0.3),
                    'waist_circumference': _to_decimal(72 + (idx % 14) + (5 - point) * 0.4),
                    'hip_circumference': _to_decimal(92 + (idx % 10) + (5 - point) * 0.3),
                    'chest_circumference': _to_decimal(90 + (idx % 12) + (5 - point) * 0.2),
                    'arm_circumference': _to_decimal(28 + (idx % 7) + point * 0.1),
                    'notes': f"Olcum nokta {point + 1}. {MOCK_TAG}",
                },
            )


def _create_or_update_appointments(apps, patient_rows):
    Appointment = apps.get_model('appointments', 'Appointment')

    today = date.today()
    week_start = today - timedelta(days=today.weekday())

    for idx, payload in enumerate(patient_rows):
        patient = payload['user']
        dietitian = payload['dietitian']

        slot_1 = APPOINTMENT_SLOTS[idx % len(APPOINTMENT_SLOTS)]
        slot_2 = APPOINTMENT_SLOTS[(idx + 2) % len(APPOINTMENT_SLOTS)]
        slot_3 = APPOINTMENT_SLOTS[(idx + 4) % len(APPOINTMENT_SLOTS)]

        past_date = week_start - timedelta(days=7 - (idx % 4))
        current_week_date = week_start + timedelta(days=idx % 7)
        next_week_date = week_start + timedelta(days=7 + (idx % 7))

        current_week_status = 'scheduled' if current_week_date >= today else 'completed'
        next_week_status = 'cancelled' if idx % 4 == 0 else 'scheduled'

        rows = [
            (past_date, slot_1, 45, 'completed', 'Gecmis kontrol randevusu'),
            (current_week_date, slot_2, 30, current_week_status, 'Bu hafta takip gorusmesi'),
            (next_week_date, slot_3, 30, next_week_status, 'Gelecek hafta planlama seansi'),
        ]

        for appt_date, appt_time, duration, status, note in rows:
            Appointment.objects.update_or_create(
                dietitian=dietitian,
                patient=patient,
                date=appt_date,
                time=appt_time,
                defaults={
                    'duration': duration,
                    'status': status,
                    'notes': f"{note}. {MOCK_TAG}",
                },
            )


def _create_or_update_foods(apps, dietitians):
    Food = apps.get_model('diets', 'Food')

    foods = []
    for idx, spec in enumerate(FOOD_SPECS):
        name, portion_size, unit, calories, protein, carbs, fats, fiber = spec
        created_by = None if idx < 5 else dietitians[idx % len(dietitians)]

        food, _ = Food.objects.update_or_create(
            name=name,
            defaults={
                'portion_size': _to_decimal(portion_size),
                'unit': unit,
                'calories': _to_decimal(calories),
                'protein': _to_decimal(protein),
                'carbs': _to_decimal(carbs),
                'fats': _to_decimal(fats),
                'fiber': _to_decimal(fiber),
                'created_by': created_by,
            },
        )
        foods.append(food)

    return foods


def _create_or_update_meals_for_plan(apps, plan, foods, offset, meal_count):
    Meal = apps.get_model('diets', 'Meal')
    MealFood = apps.get_model('diets', 'MealFood')

    for order, (meal_type, meal_time, description) in enumerate(MEAL_TEMPLATES[:meal_count], start=1):
        meal, _ = Meal.objects.update_or_create(
            diet_plan=plan,
            meal_type=meal_type,
            order=order,
            defaults={
                'time': meal_time,
                'description': f"{description} {MOCK_TAG}",
            },
        )

        food_a = foods[(offset + (order * 2)) % len(foods)]
        food_b = foods[(offset + (order * 2) + 1) % len(foods)]

        MealFood.objects.update_or_create(
            meal=meal,
            food=food_a,
            defaults={'quantity': _to_decimal('1.00')},
        )
        MealFood.objects.update_or_create(
            meal=meal,
            food=food_b,
            defaults={'quantity': _to_decimal('0.75')},
        )


def _create_or_update_diet_plans(apps, patient_rows, foods):
    DietPlan = apps.get_model('diets', 'DietPlan')
    today = date.today()

    for idx, payload in enumerate(patient_rows):
        patient = payload['user']
        dietitian = payload['dietitian']

        old_plan_title = f"Mock Baslangic Plani - {patient.first_name} {patient.last_name}"
        current_plan_title = f"Mock Guncel Plan - {patient.first_name} {patient.last_name}"

        old_start = today - timedelta(days=120 + (idx % 20))
        old_end = old_start + timedelta(days=45)

        old_plan, _ = DietPlan.objects.update_or_create(
            patient=patient,
            dietitian=dietitian,
            title=old_plan_title,
            defaults={
                'description': f"Ilk asama diyet plani. {MOCK_TAG}",
                'start_date': old_start,
                'end_date': old_end,
                'daily_calories_target': 1900 + (idx % 6) * 80,
                'is_active': False,
            },
        )

        current_start = today - timedelta(days=21 + (idx % 10))
        current_end = today + timedelta(days=35 + (idx % 8)) if idx % 5 != 0 else None
        current_plan, _ = DietPlan.objects.update_or_create(
            patient=patient,
            dietitian=dietitian,
            title=current_plan_title,
            defaults={
                'description': f"Guncel takip plani. {MOCK_TAG}",
                'start_date': current_start,
                'end_date': current_end,
                'daily_calories_target': 1700 + (idx % 7) * 90,
                'is_active': True,
            },
        )

        _create_or_update_meals_for_plan(apps, old_plan, foods, offset=idx, meal_count=4)
        _create_or_update_meals_for_plan(apps, current_plan, foods, offset=idx + 3, meal_count=6)


def _create_or_update_blog_data(apps, dietitians):
    Category = apps.get_model('blog', 'Category')
    Post = apps.get_model('blog', 'Post')

    categories = []
    for name, slug, description in CATEGORY_SPECS:
        category, _ = Category.objects.update_or_create(
            slug=slug,
            defaults={'name': name, 'description': description},
        )
        categories.append(category)

    now = timezone.now()
    for idx, dietitian in enumerate(dietitians):
        for post_index in range(2):
            is_published = post_index == 0
            slug = f"mock-{dietitian.first_name.lower()}-{idx + 1}-{post_index + 1}"
            category = categories[(idx + post_index) % len(categories)]

            published_date = None
            if is_published:
                published_date = now - timedelta(days=(idx * 4) + post_index + 1)

            Post.objects.update_or_create(
                slug=slug,
                defaults={
                    'title': f"Mock Yazi {dietitian.first_name} #{post_index + 1}",
                    'content': (
                        f"Bu bir mock blog icerigidir. Diyetisyen: {dietitian.first_name} {dietitian.last_name}. "
                        f"Kategori: {category.name}. {MOCK_TAG}"
                    ),
                    'excerpt': f"Mock ozet metni - {dietitian.first_name} #{post_index + 1}. {MOCK_TAG}",
                    'author': dietitian,
                    'category': category,
                    'featured_image': f"blog/mock-{idx + 1}-{post_index + 1}.jpg",
                    'is_published': is_published,
                    'published_date': published_date,
                    'views_count': 120 + (idx * 17) + (post_index * 11),
                },
            )


def create_mock_data(apps, schema_editor):
    dietitians = _create_or_update_dietitians(apps)
    patient_rows = _create_or_update_patients(apps, dietitians)

    _create_or_update_measurements(apps, patient_rows)
    _create_or_update_appointments(apps, patient_rows)

    foods = _create_or_update_foods(apps, dietitians)
    _create_or_update_diet_plans(apps, patient_rows, foods)

    _create_or_update_blog_data(apps, dietitians)


def delete_mock_data(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Appointment = apps.get_model('appointments', 'Appointment')
    Measurement = apps.get_model('patients', 'Measurement')
    DietPlan = apps.get_model('diets', 'DietPlan')
    Food = apps.get_model('diets', 'Food')
    Category = apps.get_model('blog', 'Category')
    Post = apps.get_model('blog', 'Post')

    Post.objects.filter(slug__startswith='mock-').delete()
    Category.objects.filter(slug__startswith='mock-').delete()

    Appointment.objects.filter(notes__contains=MOCK_TAG).delete()
    Measurement.objects.filter(notes__contains=MOCK_TAG).delete()

    DietPlan.objects.filter(Q(title__startswith='Mock ') | Q(description__contains=MOCK_TAG)).delete()
    Food.objects.filter(name__startswith='Mock ').delete()

    User.objects.filter(
        Q(email='ayse@ayse.com')
        | Q(email='elif@patient.com')
        | Q(email__endswith='@mockdiet.com')
        | Q(email__endswith='@mockpatient.com')
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        ('diets', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_mock_data, delete_mock_data),
    ]
