# Generated by Django 4.2.7 on 2026-01-18 12:43

from django.db import migrations
from django.contrib.auth.hashers import make_password
from datetime import date, time, timedelta
from django.utils import timezone


def create_mock_data(apps, schema_editor):
    """
    Mock veriler oluşturur:
    - 5 Diyetisyen
    - Her diyetisyenin 5 hastası (toplam 25 hasta)
    - 1 test diyetisyen hesabı (ayse@ayse.com / ayse)
    - Randevular, ölçümler, diyet planları
    """
    User = apps.get_model('accounts', 'User')
    DietitianProfile = apps.get_model('accounts', 'DietitianProfile')
    PatientProfile = apps.get_model('accounts', 'PatientProfile')
    Appointment = apps.get_model('appointments', 'Appointment')
    Measurement = apps.get_model('patients', 'Measurement')
    DietPlan = apps.get_model('diets', 'DietPlan')
    Food = apps.get_model('diets', 'Food')
    Meal = apps.get_model('diets', 'Meal')
    MealFood = apps.get_model('diets', 'MealFood')

    # Diyetisyen bilgileri
    dietitians_data = [
        {
            'email': 'ayse@ayse.com',
            'password': 'ayse',
            'first_name': 'Ayşe',
            'last_name': 'Kaya',
            'bio': 'Spor beslenmesi ve kilo yönetimi konusunda uzman diyetisyen',
            'specialization': 'Spor Beslenmesi',
            'experience_years': 8,
            'city': 'İstanbul'
        },
        {
            'email': 'mehmet@diet.com',
            'password': 'mehmet123',
            'first_name': 'Mehmet',
            'last_name': 'Demir',
            'bio': 'Metabolik hastalıklar ve diabet diyeti uzmanı',
            'specialization': 'Metabolik Hastalıklar',
            'experience_years': 12,
            'city': 'Ankara'
        },
        {
            'email': 'zeynep@diet.com',
            'password': 'zeynep123',
            'first_name': 'Zeynep',
            'last_name': 'Yıldız',
            'bio': 'Çocuk beslenmesi ve alerji diyetleri konusunda deneyimli',
            'specialization': 'Çocuk Beslenmesi',
            'experience_years': 6,
            'city': 'İzmir'
        },
        {
            'email': 'ahmet@diet.com',
            'password': 'ahmet123',
            'first_name': 'Ahmet',
            'last_name': 'Şahin',
            'bio': 'Kardiyovasküler sağlık ve anti-aging beslenme programları',
            'specialization': 'Kardiyovasküler Sağlık',
            'experience_years': 15,
            'city': 'Bursa'
        },
        {
            'email': 'fatma@diet.com',
            'password': 'fatma123',
            'first_name': 'Fatma',
            'last_name': 'Arslan',
            'bio': 'Hamilelik ve emzirme dönemi beslenme danışmanı',
            'specialization': 'Hamilelik Beslenmesi',
            'experience_years': 10,
            'city': 'Antalya'
        }
    ]

    # Hasta isimleri
    patient_names = [
        ('Elif', 'Çelik'), ('Can', 'Aydın'), ('Selin', 'Kurt'), ('Burak', 'Özdemir'), ('Deniz', 'Yılmaz'),
        ('Ece', 'Aksoy'), ('Mert', 'Koç'), ('İrem', 'Erdoğan'), ('Emre', 'Çetin'), ('Aylin', 'Polat'),
        ('Oğuz', 'Karaca'), ('Gizem', 'Yıldırım'), ('Kerem', 'Acar'), ('Pınar', 'Başaran'), ('Onur', 'Güneş'),
        ('Ceyda', 'Durmaz'), ('Barış', 'Özkan'), ('Naz', 'Şen'), ('Alper', 'Kılıç'), ('Esra', 'Özgür'),
        ('Tolga', 'Yaman'), ('Duygu', 'Tekin'), ('Cem', 'Aslan'), ('Merve', 'Kara'), ('Kaan', 'Doğan')
    ]

    dietitians = []

    # Diyetisyenleri oluştur
    for idx, d_data in enumerate(dietitians_data):
        if not User.objects.filter(email=d_data['email']).exists():
            dietitian = User.objects.create(
                email=d_data['email'],
                first_name=d_data['first_name'],
                last_name=d_data['last_name'],
                user_type='dietitian',
                is_staff=False,
                is_superuser=False,
                is_active=True,
                password=make_password(d_data['password'])
            )

            DietitianProfile.objects.create(
                user=dietitian,
                bio=d_data['bio'],
                specialization=d_data['specialization'],
                experience_years=d_data['experience_years'],
                city=d_data['city']
            )

            dietitians.append(dietitian)

    # Her diyetisyen için 5 hasta oluştur
    patient_idx = 0
    for dietitian in dietitians:
        for i in range(5):
            if patient_idx >= len(patient_names):
                break

            first_name, last_name = patient_names[patient_idx]
            email = f"{first_name.lower()}@patient.com"

            if not User.objects.filter(email=email).exists():
                patient = User.objects.create(
                    email=email,
                    first_name=first_name,
                    last_name=last_name,
                    user_type='patient',
                    is_staff=False,
                    is_superuser=False,
                    is_active=True,
                    password=make_password('123456')
                )

                # Rastgele boy, kilo ve hedef kilo
                height = 155 + (patient_idx * 3) % 30
                current_weight = 60 + (patient_idx * 5) % 40
                target_weight = current_weight - (5 + patient_idx % 10)

                PatientProfile.objects.create(
                    user=patient,
                    dietitian=dietitian,
                    date_of_birth=date(1985 + patient_idx % 20, 1 + patient_idx % 12, 1 + patient_idx % 28),
                    gender='F' if patient_idx % 2 == 0 else 'M',
                    height=height,
                    current_weight=current_weight,
                    target_weight=target_weight
                )

                # Her hasta için 2-3 ölçüm ekle
                for m in range(2):
                    Measurement.objects.create(
                        patient=patient,
                        date=date.today() - timedelta(days=30 * m),
                        weight=current_weight + m * 2,
                        body_fat_percentage=20 + patient_idx % 15,
                        muscle_mass=30 + patient_idx % 10,
                        waist_circumference=75 + patient_idx % 20,
                        hip_circumference=95 + patient_idx % 15
                    )

                # Bazı hastalar için randevu oluştur
                if patient_idx % 3 == 0:
                    Appointment.objects.create(
                        dietitian=dietitian,
                        patient=patient,
                        date=date.today() + timedelta(days=7 + patient_idx % 14),
                        time=time(9 + patient_idx % 8, 0),
                        duration=30,
                        status='scheduled',
                        notes='İlk konsültasyon'
                    )

                # Bazı hastalar için diyet planı oluştur
                if patient_idx % 2 == 0:
                    DietPlan.objects.create(
                        patient=patient,
                        dietitian=dietitian,
                        title=f"{first_name} için Kilo Verme Programı",
                        description='Dengeli beslenme ve düzenli egzersiz programı',
                        start_date=date.today() - timedelta(days=14),
                        daily_calories_target=1800 + patient_idx * 50,
                        is_active=True
                    )

            patient_idx += 1

    # Bazı temel besinler ekle
    foods_data = [
        ('Yulaf', 100, 'g', 389, 16.9, 66.3, 6.9, 10.6),
        ('Tavuk Göğsü', 100, 'g', 165, 31.0, 0, 3.6, 0),
        ('Yumurta', 1, 'adet', 78, 6.3, 0.6, 5.3, 0),
        ('Muz', 1, 'adet', 105, 1.3, 27, 0.4, 3.1),
        ('Brokoli', 100, 'g', 34, 2.8, 7, 0.4, 2.6),
        ('Somon', 100, 'g', 208, 20.4, 0, 13.4, 0),
        ('Badem', 30, 'g', 170, 6.0, 6.0, 15.0, 3.5),
        ('Elma', 1, 'adet', 95, 0.5, 25, 0.3, 4.4),
        ('Pirinç', 100, 'g', 130, 2.7, 28.2, 0.3, 0.4),
        ('Zeytinyağı', 15, 'ml', 120, 0, 0, 14.0, 0),
    ]

    for food_data in foods_data:
        name, portion, unit, cal, protein, carbs, fats, fiber = food_data
        if not Food.objects.filter(name=name).exists():
            Food.objects.create(
                name=name,
                portion_size=portion,
                unit=unit,
                calories=cal,
                protein=protein,
                carbs=carbs,
                fats=fats,
                fiber=fiber
            )


def delete_mock_data(apps, schema_editor):
    """Migration geri alınırsa mock verileri sil"""
    User = apps.get_model('accounts', 'User')

    # Mock diyetisyenleri sil
    User.objects.filter(email__in=[
        'ayse@ayse.com', 'mehmet@diet.com', 'zeynep@diet.com',
        'ahmet@diet.com', 'fatma@diet.com'
    ]).delete()

    # Mock hastaları sil (email pattern'e göre)
    User.objects.filter(email__endswith='@patient.com').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_mock_data, delete_mock_data),
    ]
