# Generated by Django 5.2.11 on 2026-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_mock_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=5, verbose_name='Tercih Edilen Dil'),
        ),
    ]
