# Generated by Django 4.2.7 on 2026-01-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kilo (kg)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Yağ Oranı (%)')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kas Kütlesi (kg)')),
                ('waist_circumference', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bel Çevresi (cm)')),
                ('hip_circumference', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Kalça Çevresi (cm)')),
                ('chest_circumference', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Göğüs Çevresi (cm)')),
                ('arm_circumference', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Kol Çevresi (cm)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL, verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Ölçüm',
                'verbose_name_plural': 'Ölçümler',
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
